name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Dart/Flutter Package Analyzer
        uses: axel-op/dart-package-analyzer@v2
      - name: Run tests
        run: pub run test
